sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/Competitor_Market_Analysis__c.object-meta.xml
<CustomObject>
    <label>Competitor Market Analysis</label>
    <nameField>
        <displayFormat>CMA-{0000}</displayFormat>
        <label>Competitor Market Analysis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Market Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitor Market Analysis</relationshipLabel>
    <relationshipName>Competitor_Market_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Analysis_Date__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Date__c</fullName>
    <label>Analysis Date</label>
    <type>Date</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <label>Competitor Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Competitor_Price__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Price__c</fullName>
    <label>Competitor Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Competitor_Product__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product__c</fullName>
    <label>Competitor Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Competitor_Stock__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Stock__c</fullName>
    <label>Competitor Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Customer_Demand_Trend__c.field-meta.xml
<CustomField>
    <fullName>Customer_Demand_Trend__c</fullName>
    <label>Customer Demand Trend</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Increasing</fullName>
            </value>
            <value>
                <fullName>Stable</fullName>
            </value>
            <value>
                <fullName>Decreasing - Ours</fullName>
            </value>
            <value>
                <fullName>Increasing - Competitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Dealer_Preference__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Preference__c</fullName>
    <label>Dealer Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strongly</fullName>
            </value>
            <value>
                <fullName>Slightly Prefer Ours</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Slightly</fullName>
            </value>
            <value>
                <fullName>Strongly Prefer Competitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Display_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Display_Visibility__c</fullName>
    <label>Display Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excellent</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Not Displayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Our_Price__c.field-meta.xml
<CustomField>
    <fullName>Our_Price__c</fullName>
    <label>Our Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Our_Stock__c.field-meta.xml
<CustomField>
    <fullName>Our_Stock__c</fullName>
    <label>Our Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Price_Difference_INR__c.field-meta.xml
<CustomField>
    <fullName>Price_Difference_INR__c</fullName>
    <formula>Our_Price__c -  Competitor_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Difference (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Price_Sensitivity__c.field-meta.xml
<CustomField>
    <fullName>Price_Sensitivity__c</fullName>
    <label>Price Sensitivity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Promo_Scheme_Active__c.field-meta.xml
<CustomField>
    <fullName>Promo_Scheme_Active__c</fullName>
    <label>Promo / Scheme Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No / Yes - Ours</fullName>
            </value>
            <value>
                <fullName>Yes - Competitor</fullName>
            </value>
            <value>
                <fullName>Yes - Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Shelf_Share_Percent__c.field-meta.xml
<CustomField>
    <fullName>Shelf_Share_Percent__c</fullName>
    <label>Shelf Share Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Stock_Ratio__c.field-meta.xml
<CustomField>
    <fullName>Stock_Ratio__c</fullName>
    <formula>Our_Stock__c / (Our_Stock__c + Competitor_Stock__c) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stock Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfa-dms/force-app/main/default/objects/Competitor_Market_Analysis__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Competitor Market Analysis</relationshipLabel>
    <relationshipName>Competitor_Market_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

sfa-dms/force-app/main/default/classes/CompetitorAnalysisController.cls
public with sharing class CompetitorAnalysisController {

    @AuraEnabled
    public static Id saveCompetitorAnalysis(
        Id      visitId,
        String  competitorName,
        String  competitorProduct,
        Decimal competitorPrice,
        Integer competitorStock,
        Integer ourStock,
        Decimal ourPrice,
        Decimal shelfSharePercent,
        String  displayVisibility,
        String  promoActive,
        String  dealerPreference,
        String  demandTrend,
        String  priceSensitivity,
        String  remarks
    ) {

        System.debug('Market competitor Analysis active');
        // Fetch Account from Visit
        Visit__c visit = [
            SELECT Id, Account__c
            FROM   Visit__c
            WHERE  Id = :visitId
            LIMIT  1
        ];

        Competitor_Market_Analysis__c rec = new Competitor_Market_Analysis__c(
            Visit__c              = visitId,
            Account__c            = visit.Account__c,
            Competitor_Name__c    = competitorName,
            Competitor_Product__c = competitorProduct,
            Competitor_Price__c   = competitorPrice,
            Competitor_Stock__c   = competitorStock,
            Our_Stock__c          = ourStock,
            Our_Price__c          = ourPrice,
            Shelf_Share_Percent__c= shelfSharePercent,
            Display_Visibility__c = displayVisibility,
            Promo_Scheme_Active__c       = promoActive,
            Dealer_Preference__c  = dealerPreference,
            Customer_Demand_Trend__c       = demandTrend,
            Price_Sensitivity__c  = priceSensitivity,
            Analysis_Date__c      = Date.today()
        );

        insert rec;
        return rec.Id;
    }

    @AuraEnabled(cacheable=true)
    public static List<Competitor_Market_Analysis__c> getVisitCompetitorAnalysis(Id visitId) {
        return [
            SELECT Id, Competitor_Name__c, Competitor_Product__c,
                   Competitor_Price__c, Our_Price__c,
                   Competitor_Stock__c, Our_Stock__c,
                   Shelf_Share_Percent__c, Display_Visibility__c,
                   Promo_Scheme_Active__c, Dealer_Preference__c,
                   Customer_Demand_Trend__c, Price_Sensitivity__c,
                   CreatedDate,
                   Price_Difference_INR__c, Stock_Ratio__c
            FROM   Competitor_Market_Analysis__c
            WHERE  Visit__c = :visitId
            ORDER BY CreatedDate DESC
        ];
    }
}